### ISSUE TITLE
Adding description and different widths to Sidebar component

### ISSUE THREAD

**Issue by nikola-nulogy** [nulogy/design-system#1293]
### Is your feature request related to a problem? If so, please describe.

In order to accommodate different types of content(tables, 2/3-column layouts, ...) we would like to have control over the width of the sidebar. Also, we would like to add a description line under the title so that complex concepts can be explained in more detail.

### Is your team blocked from moving forward by the lack of this functionality/behaviour?

No. The team can default to an alternative solution that would provide inferior UX.

### Do you have an alternative solution for the problem?

An alternative to this is using existing capabilities of the component that provide an acceptable (but inferior) experience.

### Have you consulted and have an alignment with the product designer?

- [X] Yes
- [ ] No

### Who would you like to execute this feature?

- [ ] Myself
- [X] DesignOps

### Helpful resources

For design specs please follow [Figma UI kit](https://www.figma.com/file/IH4gk9P2E4xEYiNKoD22Jd/NDS-v1?type=design&node-id=5634-1061&mode=design&t=TSdGpM141BSsgAHz-4).
More info available in [Jira ticket](https://nulogy-go.atlassian.net/browse/DES-518).

### Additional context

Regarding component width, Hiba is looking into additional widths, so the widths may need to be updated soon.

**Comment by haideralsh** [comment]
@nikola-nulogy What is the desired behaviour for the SideBar when someone passes a width value that is other than the predefined ones? Should we permit that? If not, this will be a breaking change for our existing sidebars
