### ISSUE TITLE
Upgrade styled-components to version 6

### ISSUE THREAD

**Issue by jchunky** [nulogy/design-system#1294]
### Please describe your request

I'm trying to upgrade styled-components in Production Scheduling from version 5 to version 6. When I do that, the BrandedNavBar fails. My hypothesis is that the failure is in the NDS code. Would you be able to upgrade styled-components in NDS to version 6? Once that's done, I'm assuming it will resolve my issue.

**Comment by haideralsh** [comment]
@jchunky What is the error you're getting? Is this a CI error or a run time error?

**Comment by haideralsh** [comment]
@jchunky I was able to reproduce these errors [here](https://github.com/nulogy/design-system/pull/1296). 

When does your team need to upgrade? and is anyone from your team able to work on the PR?

**Comment by haideralsh** [comment]
Hey @jchunky, can you let me know if this is a blocker for your team and if your team has capacity to work on this?

**Comment by jchunky** [comment]
> @jchunky What is the error you're getting? Is this a CI error or a run time error?

When I click on a dropdown menu in BrandedNavbar, it throws an exception.

**Comment by jchunky** [comment]
> @jchunky I was able to reproduce these errors [here](https://github.com/nulogy/design-system/pull/1296).
> 
> When does your team need to upgrade? and is anyone from your team able to work on the PR?

There's no rush. The only thing this blocks is upgrading styled-components for us, which we were upgrading as part of our routine process to upgrade libraries.

**Comment by jchunky** [comment]
> Hey @jchunky, can you let me know if this is a blocker for your team and if your team has capacity to work on this?

This doesn't block any features or tickets. It's just part of our routine process to upgrade third-party libraries, since Production Scheduling uses styled-components. 

We're available to pair with you.

**Comment by haideralsh** [comment]
@jchunky are there specific features in v6 that you’re interested in? I tried upgrading to the [latest from v5](https://styled-components.com/releases#v5.3.11) which was released in May this year and it built without errors. We might not have capacity in design-ops to do the full v6 upgrade at the moment. Does this address the issue you were having?

**Comment by haideralsh** [comment]
After discussion with @jchunky we decided to upgrade to the latest 5.x.x version. The team will update NDS on their end and we will reopen this issue if needed. 

See [release](https://github.com/nulogy/design-system/releases/tag/v8.17.0).
