### ISSUE TITLE
Select component has multiple scrollbars

### ISSUE THREAD

**Issue by navilau** [nulogy/design-system#1326]
### Describe the bug

NDS version - 8.15.2
In the /events search page on CPI [https://qa-connect.nulogy.net/events],
if you review the select boxes on the page, ex event type, you will see 3 scroll bars - 2 at the bottom, and 1 on the right.

### Steps to reproduce

1. Navigate to reactified events page on CPI https://qa-connect.nulogy.net/events
2. Click on Event Type to scroll through the list
Observe three scroll bars. 

This is also the case with Source Tenant field (2 scroll bars on the right)

### Expected behaviour

We should see just one on the right, and 1 on the bottom if the select box is not wide enough. We do not see this behaviour on other pages where the Select component spans the full page.

### Is your team blocked from moving forward by the bug?

We want to release this behaviour to production, but without these UI bugs ASAP. (next week)

### Who would you like to fix the bug?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

Dec 11

### Additional context

ensure the feature toggle for events_react_index is enabled
see screenshot attached
![Screenshot 2023-12-04 at 3 04 38 PM (2)](https://github.com/nulogy/design-system/assets/18558840/46d683ce-cbc9-4f3a-9611-2f28c31a1d9a)

**Comment by haideralsh** [comment]
@navilau I paired with Rebekah and we weren't able to reproduce this locally. I will close this for now but I am happy to pair again in the future to help resolve this.
