### ISSUE TITLE
Add Signpost icon to NDS

### ISSUE THREAD

**Issue by vincentkoo7** [nulogy/design-system#1431]
### Is your feature request related to a problem? If so, please describe.

We are looking to add a new button to the MIA page in SF to trigger a Pendo guide. We want to use the same **signpost** icon that is being used in the SC navbar for Guided Tours. 

### Is your team blocked from moving forward by the lack of this functionality/behaviour?

The team needs the icon to add the button to the page.

### Have you consulted and have an alignment with the product designer?

- [X] Yes
- [ ] No

### Who would you like to execute this feature?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

September 4

### Helpful resources

[Material Symbols: signpost](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:signpost:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=post&icon.size=24&icon.color=%235f6368)

**Comment by haideralsh** [comment]
Fixed by https://github.com/nulogy/design-system/pull/1432
