### ISSUE TITLE
Allow left and right icons in input fields

### ISSUE THREAD

**Issue by vincentkoo7** [nulogy/design-system#1471]
### Is your feature request related to a problem? If so, please describe.

I'm looking to include search and barcode icons on the left side of input fields for the future mobile cycle count work. That work is expected to begin at the end of November/start of December.

### Is your team blocked from moving forward by the lack of this functionality/behaviour?

No, we could proceed with the current input with placeholder text.

### Have you consulted and have an alignment with the product designer?

- [X] Yes
- [ ] No

### Who would you like to execute this feature?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

End of November

### Helpful resources

**Wireframe for mobile CC with left-aligned barcode icon**:
![image](https://github.com/user-attachments/assets/332dce2b-4b6b-435f-ba35-60af1b53711f)

**Existing input for global search in SC**:
![image](https://github.com/user-attachments/assets/1169940b-8d3b-4601-b8e9-0470ddad95ff)

**Existing input for PO search in Purchase orders module in SC**:
- The right icon in this case is actually a button, but I believe this is the only instance of this across the apps so I'm not sure if an iconic button should be part of the input component.
![image](https://github.com/user-attachments/assets/343375e1-c41e-40bc-ab40-aae9bad85c89)

**Comment by haideralsh** [comment]
Fixed with https://github.com/nulogy/design-system/pull/1468/commits/e9dbddb6e650525377338f2836ed0194d754ca49 and available on the next channel.
