### ISSUE TITLE
Cannot open submenus in the NDS navbar (on Firefox only)

### ISSUE THREAD

**Issue by navilau** [nulogy/design-system#1488]
### Describe the bug

Attempt to open a dropdown menu and navigate to a sub-menu, it does not work on Firefox but works on Chrome.
This should be cross browser compatible

### Steps to reproduce

1. Login to Shopfloor NA or CPI Portal Dashboard on Firefox and Chrome
2. Attempt to open a dropdown menu and navigate to a sub-menu on Firefox 

### Expected behaviour

I should be able to navigate to the sub-menu option easily but I cannot get it to stay open and click on the option to navigate to the path on Firefox.

### Is your team blocked from moving forward by the bug?

No, ideally we would like this fixed before the launch date (Jan 7 2025) as some of our customers could be using firefox.

### Who would you like to fix the bug?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

Before Jan 7

### Helpful resources

https://github.com/user-attachments/assets/a6518efe-2b00-44bd-8a02-e8e9914bd512

**Comment by haideralsh** [comment]
hey @navilau are you able to reproduce this in [Storybook](https://5f60c6c285eaad0022dce67f-krnhtcnree.chromatic.com/) in FireFox? I wasn't able to do that.

**Comment by navilau** [comment]
https://github.com/user-attachments/assets/cd4d53a9-e03a-4760-b59d-e8333a63b8da

Yes, I am seeing the same issue on Firefox in Storybook as well!

**Comment by navilau** [comment]
I restarted my firefox, and that seemed to fix the issue
