### ISSUE TITLE
Security problem in `plop` library

### ISSUE THREAD

**Issue by danambrogio** [nulogy/design-system#388]
The `handlebars` library has a security problem, and has released a patch. Looking at our (GO's) dependency tree, `handlebars` is used by `node-plop`, `node-plop` is used by `plop`, and `plop` is used by NDS.

While we wait for dependencies to release patched versions, we've fixed this in GO for now with a 'resolution' in package.json:

`
"resolutions": {
    "**/**/handlebars": ">=4.3.0"
  }
`

https://www.npmjs.com/advisories/1164

**Comment by matthewlyle** [comment]
This was fixed with https://github.com/nulogy/design-system/pull/390 and released in [v0.13.2](https://github.com/nulogy/design-system/releases/tag/v0.13.2)
